
import {
  ListChecks,
  LayoutDashboard,
  PlusCircle,
  GripVertical,
  Edit3,
  Trash2,
  UserCircle,
  CalendarDays,
  Loader2,
  Sparkles,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  Rocket,
  BarChart3,
  FolderPlus,
  Layers3,
  Map,
  RefreshCw,
  Eye,
  Briefcase,
  Pencil,
  Moon,
  Sun,
  ClipboardList,
  BookText,
  Bug,
  Milestone,
  CornerDownRight,
  Lightbulb,
  Users2,
  Users,
  UserPlus,
  PlusSquare,
  MessageSquare,
  ArrowLeft,
  ChevronLeft,
  MessageSquarePlus,
  LogOut,
  Bell,
  Archive,
  Compass, 
  CalendarClock, // Added for Past Due or specific date-related items
} from 'lucide-react';

export const Icons = {
  Logo: Compass, 
  Dashboard: LayoutDashboard,
  Add: PlusCircle,
  DragHandle: GripVertical,
  Edit: Edit3,
  Delete: Trash2,
  User: UserCircle,
  Calendar: CalendarDays, // Generic calendar
  Spinner: Loader2,
  Sparkles: Sparkles,
  Warning: AlertTriangle, // Good for Past Due
  Success: CheckCircle2,
  Error: XCircle,
  Info: Info, // Good for Unscheduled or general info
  Project: Rocket,
  ProjectsPage: Briefcase,
  Reports: BarChart3,
  AddProject: FolderPlus,
  Backlog: Layers3,
  Roadmap: Map,
  Sprint: RefreshCw,
  View: Eye,
  ListChecks: ListChecks, // Generic task/list
  Rename: Pencil,
  Moon: Moon,
  Sun: Sun,
  IssueTask: ClipboardList,
  IssueStory: BookText,
  IssueBug: Bug,
  IssueEpic: Milestone,
  IssueSubtask: CornerDownRight,
  IssueFeatureRequest: Lightbulb,
  Users: Users2,
  Team: Users,
  AddUser: UserPlus,
  AddTeam: PlusSquare,
  Chat: MessageSquare,
  ArrowLeft: ArrowLeft,
  ChevronLeft: ChevronLeft,
  MessageSquarePlus: MessageSquarePlus,
  Edit3: Edit3,
  LogOut: LogOut,
  Bell: Bell,
  Archive: Archive,
  CalendarClock: CalendarClock, // For more specific time-related items
  // Adding issue type icons directly to Icons for easier access in RoadmapTaskCard
  task: ClipboardList,
  story: BookText,
  bug: Bug,
  epic: Milestone,
  subtask: CornerDownRight,
  feature_request: Lightbulb,
};

export type IconName = keyof typeof Icons;
